version: 2.1
jobs:
  build:
    machine:
      image: ubuntu
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: docker build
          command: DOCKER_BUILDKIT=1 docker build -t $DOCKER_IMAGE --build-arg BUILDKIT_INLINE_CACHE=1 .
      - run:
          name : docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: docker push
          command: docker push $DOCKER_IMAGE:latest
